services:
  fastapi:
    build: ./backend/fastapi
    networks:
      - app-network

  nginx:
    build: ./Frontend/nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge