events{}

http{
    include /etc/nginx/mime.types;

    # Rate limiting with a zone of 10MB and a request rate of 10 per second
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    # The fastapi server address and port
    upstream fastapi_server{
        server fastapi:8000;
    }

    server {
        # Listen on port 80 for incoming HTTP requests
        listen 80;
        
        location / {
        }

        location /api/ {
            # Rate limiting allows an initial burst of 20 request. After that it is 10 request per second
            limit_req zone=api_limit burst=20;
            # Forward requests to the Uvicorn server running on port 8000 (the trailing / after 8000 is important because this will replace the /api/ and add what ever URI path comes after it!)
            proxy_pass http://fastapi:8000/;

            # Set headers to pass client information to the FastAPI app
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Proxy websocket connections for FastAPI which is mounted under /api/
        location /api/ws/ {
            # Map /api/ws/... to the backend's /ws/... endpoints
            proxy_pass http://fastapi_server/ws/;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }


        # When the OpenAPI documentation is requested via /api/docs it requests the openapi.json file documentation
        # from the url /openapi.json using a GET request.
        # The FastAPI sits behind the nginx reverse proxy because the GET request to /openapi.json doesn't work and
        # has to be rewriten into a GET request to the url /api/openapi.json.
        location /openapi.json {
            rewrite ^ /api/openapi.json last;
        }
    }
}